version: '3'
services: 
  postgres:
    image: 'postgres:11'
  redis:
    image: 'redis:latest'
  server:
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - /app/node_modules
      - ./server:/app